version: '3.8'

services:
  db:
    image: postgres:15
    container_name: event-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: event-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eventdb
      PORT: 3000
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  pgdata:
